# Generated by Django 4.0.1 on 2022-05-15 19:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('text', models.TextField(default='Your description')),
                ('main_metric', models.CharField(default='Main metric', max_length=100)),
                ('second_metric', models.CharField(default='Second metric', max_length=100)),
                ('power', models.FloatField(default=0.8)),
                ('significance_level', models.FloatField(default=0.05)),
                ('mde', models.FloatField(default=1)),
                ('data', models.BinaryField(default=None)),
                ('history_data', models.BinaryField(default=None)),
                ('base_link', models.TextField(default='BaseLink')),
                ('is_finished', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('finish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('control_group', models.TextField(default='')),
                ('test_group', models.TextField(default='')),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.experiment', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('confidence_interval_r', models.FloatField(default=1)),
                ('confidence_interval_l', models.FloatField(default=1)),
                ('effect_value', models.FloatField(default=1)),
                ('graph', models.BinaryField(default=None)),
                ('description', models.TextField(default='')),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.experiment', unique=True)),
            ],
        ),
    ]
