# Generated by Django 4.0.1 on 2022-05-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentresult',
            name='graph',
            field=models.TextField(default=''),
        ),
    ]
