# Generated by Django 4.0.1 on 2022-05-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_experimentresult_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentresult',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
